tegra-profiler: fix unused function build issue
fix below compilation issues pointed out by clang

eh_unwind.c:182:1: error: unused function 'prel31_to_addr'
dwarf_unwind.c:441:1: error: unused function 'set_rule_reg'
armv8_pmu.c:236:1: error: unused function 'armv8_pmu_pmintenset_read'
armv8_pmu.c:246:1: error: unused function 'armv8_pmu_pmintenset_write'
armv8_pmu.c:260:1: error: unused function 'armv8_pmu_pmovsclr_read'
armv8_pmu.c:364:1: error: unused function 'disable_interrupt'
armv8_pmu.c:612:1: error: unused function 'pmu_read_emulate'

bug 1745660

Change-Id: If4a57aa0bfc375980357e3d92bdadac0b165695a
Signed-off-by: Sri Krishna chowdary <schowdary@nvidia.com>
Reviewed-on: http://git-master/r/1171549
(cherry picked from commit 4c4d58f49c61ebfe3b729b30166ddd9fe309977d)
Reviewed-on: http://git-master/r/1249578
(cherry picked from commit fee6b59514b50811bf66f8d531fd692bce63b29e)